// Codex CLI emitter.
// - context.md      -> AGENTS.md (+ rules reference section; no @import in Codex)
// - rules/**        -> .codex/rules/** (verbatim)
// - commands/**.md  -> .codex/prompts/<flattened>.md (Codex prompts are flat + home-scoped)
// - agents/*.md     -> .codex/agents/<name>.toml (developer_instructions = body)
// - settings.json   -> .codex/config.toml (approximate)

import TOML from "@iarna/toml";
import type { PruneResult } from "../types.js";
import { resolveFiles } from "./resolve.js";
import { collectRuleEntries, renderRulesSection } from "./toc.js";
import { read, write, copy } from "./fsutil.js";
import { parse } from "../transform/frontmatter.js";

const codexRuleTarget = (destRel: string): string => `.codex/${destRel}`;

export function emitCodex(baseDir: string, outDir: string, result: PruneResult): string[] {
  const files = resolveFiles(result);
  const notes: string[] = [];

  for (const f of files) {
    switch (f.category) {
      case "context": {
        const ctx = read(baseDir, f.srcRel);
        const entries = collectRuleEntries(baseDir, files, codexRuleTarget);
        const section = renderRulesSection(entries, "프로젝트 규칙 참조");
        write(outDir, "AGENTS.md", `${ctx.trimEnd()}\n${section}`);
        break;
      }
      case "rule":
        copy(baseDir, f.srcRel, outDir, codexRuleTarget(f.destRel));
        break;
      case "command":
        write(outDir, `.codex/prompts/${flattenCommand(f.destRel)}`, toCodexPrompt(read(baseDir, f.srcRel)));
        break;
      case "agent":
        write(outDir, `.codex/agents/${agentName(read(baseDir, f.srcRel), f.destRel)}.toml`, toCodexAgent(read(baseDir, f.srcRel)));
        break;
      case "settings":
        write(outDir, ".codex/config.toml", codexConfig());
        break;
      case "misc":
        copy(baseDir, f.srcRel, outDir, codexRuleTarget(f.destRel));
        break;
    }
  }

  notes.push(
    "Codex 커스텀 프롬프트는 홈 디렉토리(`~/.codex/prompts/`)에서만 로드됩니다. 생성된 `.codex/prompts/`의 파일을 `~/.codex/prompts/`로 복사하거나 심링크하세요.",
  );
  notes.push(
    "Codex는 `AGENTS.md`의 import를 지원하지 않습니다. 규칙 파일은 참조 목차로만 링크되며, 에이전트가 필요할 때 직접 읽습니다.",
  );
  return notes;
}

// commands/rw/plan/plan.md -> rw-plan-plan.md
function flattenCommand(destRel: string): string {
  return destRel.replace(/^commands\//, "").replace(/\//g, "-");
}

function toCodexPrompt(raw: string): string {
  const { data, body } = parse(raw);
  const fm: string[] = [];
  if (data.description) fm.push(`description: ${JSON.stringify(String(data.description))}`);
  if (data["argument-hint"]) fm.push(`argument-hint: ${JSON.stringify(String(data["argument-hint"]))}`);
  const front = fm.length ? `---\n${fm.join("\n")}\n---\n\n` : "";
  // Codex uses $ARGUMENTS / $1..$9 — same tokens as the source, no rewrite needed.
  return `${front}${body}`;
}

function agentName(raw: string, destRel: string): string {
  const { data } = parse(raw);
  return String(data.name ?? destRel.split("/").pop()!.replace(/\.md$/, ""));
}

function toCodexAgent(raw: string): string {
  const { data, body } = parse(raw);
  const obj: Record<string, unknown> = {
    name: String(data.name ?? ""),
    description: String(data.description ?? ""),
    developer_instructions: body,
  };
  if (data.model && data.model !== "inherit") obj.model = String(data.model);
  return TOML.stringify(obj as TOML.JsonMap);
}

function codexConfig(): string {
  // Minimal project config. Model/approval left to the user's global config.
  return [
    "# Codex project config generated by rw-base.",
    "# See https://learn.chatgpt.com/docs/config-file/config-basic",
    'project_doc_fallback_filenames = ["AGENTS.md"]',
    "",
  ].join("\n");
}
